# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: AWS CloudFormation "Deploy CloudFormation Stack" Action for GitHub Actions
        # You may pin to the exact commit or the version.
        # uses: aws-actions/aws-cloudformation-github-deploy@dfbee8a4fec90af61b71bafda3890f8c4a2075ef
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          # The name of the CloudFormation stack
          name: 
          # The path or URL to the CloudFormation template
          template: 
          # The comma-delimited list of stack template capabilities to acknowledge. Defaults to 'CAPABILITY_IAM'
          capabilities: # optional, default is CAPABILITY_IAM
          # The parameters to override in the stack inputs. The list is comma-delimited, with each entry formatted as <ParameterName>=<ParameterValue>.
          parameter-overrides: # optional
          # If the CloudFormation change set is empty, do not fail. Defaults to '0' (will fail on empty change set)
          no-fail-on-empty-changeset: # optional, default is 0
          # Disable rollback of the stack if stack creation fails. Defaults to '0' (will rollback if stack creation fails). This input is only used for stack creation, not for stack update
          disable-rollback: # optional, default is 0
          # The amount of time that can pass before the stack status becomes CREATE_FAILED. This input is only used for stack creation, not for stack update
          timeout-in-minutes: # optional
          # The comma-delimited list of Amazon SNS topic ARNs to publish stack related events
          notification-arns: # optional
          # The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that AWS CloudFormation assumes to create the stack. AWS CloudFormation uses the role's credentials to make calls on your behalf. AWS CloudFormation always uses this role for all future operations on the stack. As long as users have permission to operate on the stack, AWS CloudFormation uses this role even if the users don't have permission to pass it. Ensure that the role grants least privilege. If you don't specify a value, AWS CloudFormation uses the role that was previously associated with the stack
          role-arn: # optional
          # Key-value pairs to associate with this stack. This input should be JSON-formatted, for example [ { "Key": "string", "Value": "string" } ]
          tags: # optional
          # Whether to enable termination protection on the specified stack. Defaults to '0' (terminated protection will be disabled) This input is only used for stack creation, not for stack update
          termination-protection: # optional, default is 0
